[package]
name = "aster"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.10.0" }
rand = { version = "0.8.5" }
serde = { version = "1.0", features = ["derive"]}
toml = "0.5"